FROM dev-base:1
MAINTAINER Richard Attermeyer "richard.attermeyer@gmail.com"

RUN apt-get update
RUN apt-get install build-essential ruby-all-dev
ADD ./prepare-vagrant-user.sh /tmp/
RUN chmod u+x /tmp/prepare-vagrant-user.sh
RUN /tmp/prepare-vagrant-user.sh 

